# Generated by Django 3.2.6 on 2021-09-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(default='', max_length=100)),
                ('profile_id', models.CharField(default='', max_length=100)),
                ('model_type', models.CharField(default='classification', max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('message', models.CharField(default='classification', max_length=1000)),
                ('epoch', models.IntegerField()),
                ('epoch_to_train', models.IntegerField()),
                ('loss', models.DecimalField(decimal_places=3, max_digits=6)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('epoch_duration', models.DecimalField(decimal_places=3, max_digits=7)),
            ],
        ),
    ]
