# Generated by Django 3.2.3 on 2021-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='accuracy',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='training',
            name='epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='training',
            name='epoch_duration',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='training',
            name='loss',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
