"""
Django settings for aitrainer project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
#from trainer.aitrainersettings import ENGINE, NAME, USER, PASSWORD, HOST, PORT
import os



# import environ
# # Initialise environment variables
# env = environ.Env()
# environ.Env.read_env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-=tot_2ooe)cpgw)!nj-_o4=a57(g8j0x6sod+o*$q((3ybg%r9'
# SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trainer',
    "sslserver",
]

MIDDLEWARE = [
        # Custom middleware
   
    'aitrainer.middleware.middlewares.TrainerMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'aitrainer.middleware.middlewares.TrainerMiddleware',
    

]

ROOT_URLCONF = 'aitrainer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aitrainer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }













# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CELERY_BROKER_URL = "amqp://guest@localhost//"

CELERY_RESULT_BACKEND = "rpc"


# Default training parameters
DEFAULT_NUM_EPOCHS=10
DEFAULT_BATCH_SIZE=24
DEFAULT_LEARNING_RATE=0.001
DEFAULT_STEP_SIZE=10
DEFAULT_GAMMA=0.5
DEFAULT_IMAGE_SIZE=224
DEFAULT_CHANNEL=3
DEFAULT_DATA_CRYPTED=False
DEFAULT_EXPORT=["pytorchmobile", "coreml"] 
ALL_POSSIBLE_EXPORT = ["tflite", "keras", "coreml", "frozen", "torch", "onnx", "pytorchmobile"]

# Parameters range
NUM_EPOCHS_MIN=1
NUM_EPOCHS_MAX=100
BATCH_SIZE_MIN=1
BATCH_SIZE_MAX=36
LEARNING_RATE_MIN=0.000001
LEARNING_RATE_MAX=0.9
STEP_SIZE_MIN=1
GAMMA_MIN=0.0001
GAMMA_MAX=0.9999
IMAGE_SIZE_MIN=64
IMAGE_SIZE_MAX=1024

# Required parameters
NB_REQUIRED_PARAMETERS=7


